### ISSUE TITLE
Documentation pleassssse

### ISSUE THREAD

**Issue by procodingtools** [baumths/flutter_tree_view#28]
**### Documentation pleassssse**

**Comment by talbiislam96** [comment]
@mbaumgartenbr  is there any documentation provided please ? I like the package but It lack s the doc it'd be helpful if you provided us wit some simple concrete code on how to use the package with a list of data

**Comment by mbaumgartenbr** [comment]
Hey @talbiislam96! Sorry for the inconvenience.

I'm actively working on version 1.0 of the package and the API changed drastically. Due to this change I decided to not write documentation for the current version and instead focus on a rich documentation for the next one.

The plan is to have a nice and easy to follow guide in README. And I'm also working on simpler examples instead of relying on the demo.

The new API is very close to done and the only thing left after that is the readme and then the release of a dev version.

Since there's many different ways of representing a tree, I won't be able to cover everything, therefore, once the new version is out, I'd be open to answering the "How to use the package with `foo` data model?" question, feel free to open question issues then.
